<?php

declare(strict_types=1);

$autoloadCandidates = [
    getcwd().'/vendor/autoload.php',
    dirname(__DIR__, 2).'/vendor/autoload.php',
    dirname(__DIR__, 3).'/vendor/autoload.php',
];

$autoloadPath = null;
foreach ($autoloadCandidates as $candidate) {
    if (is_file($candidate)) {
        $autoloadPath = $candidate;
        break;
    }
}

if ($autoloadPath === null) {
    fwrite(STDERR, "Could not locate vendor/autoload.php.\n");
    exit(1);
}

require $autoloadPath;

$options = getopt('', ['source::', 'target::', 'namespace::', 'class::']);

$sourceClass = is_string($options['source'] ?? null)
    ? $options['source']
    : 'Tests\\Feature\\TestCase';

$targetPath = is_string($options['target'] ?? null)
    ? $options['target']
    : 'tests/PHPStan/PestFeatureTestCase.php';

$targetFile = str_starts_with($targetPath, '/')
    ? $targetPath
    : getcwd().'/'.$targetPath;

$targetNamespace = is_string($options['namespace'] ?? null)
    ? $options['namespace']
    : 'Tests\\PHPStan';

$targetClass = is_string($options['class'] ?? null)
    ? $options['class']
    : 'PestFeatureTestCase';

if (! class_exists($sourceClass)) {
    fwrite(STDERR, 'Source class not found: '.$sourceClass."\n");
    exit(1);
}

$reflection = new ReflectionClass($sourceClass);

$methods = array_values(array_filter(
    $reflection->getMethods(ReflectionMethod::IS_PROTECTED),
    static function (ReflectionMethod $method): bool {
        $name = $method->getName();
        $excluded = [
            '__construct',
            '__destruct',
            '__clone',
            'assertPreConditions',
            'assertPostConditions',
        ];

        if (! str_starts_with($name, 'assert') && ! str_starts_with($name, 'expect')) {
            return false;
        }

        if ($method->isStatic() || $method->isFinal()) {
            return false;
        }

        return ! in_array($name, $excluded, true);
    }
));

usort(
    $methods,
    static fn (ReflectionMethod $a, ReflectionMethod $b): int => $a->getName() <=> $b->getName()
);

$lines = [
    '<?php',
    '',
    'declare(strict_types=1);',
    '',
    'namespace '.$targetNamespace.';',
    '',
    '/**',
    ' * PHPStan-only proxy type for Pest closure `$this`.',
    ' *',
    ' * Generated by odinns/phpstan-pest-this tools/generate-pest-proxy.php.',
    ' */',
    'abstract class '.$targetClass.' extends \\'.$sourceClass,
    '{',
];

foreach ($methods as $method) {
    $signature = buildMethodSignature($method);
    $callArgs = buildCallArguments($method);
    $returnType = $method->getReturnType();
    $returnTypeName = normalizeTypeName($returnType);
    $phpDocLines = buildMethodPhpDocLines($method, $returnType);

    if ($phpDocLines !== []) {
        $lines[] = '    /**';
        foreach ($phpDocLines as $phpDocLine) {
            $lines[] = '     * '.$phpDocLine;
        }
        $lines[] = '     */';
    }

    $lines[] = '    '.$signature;
    $lines[] = '    {';

    if ($returnTypeName === 'void' || $returnTypeName === 'never') {
        $lines[] = '        parent::'.$method->getName().'('.$callArgs.');';
    } elseif ($returnType === null) {
        $lines[] = '        parent::'.$method->getName().'('.$callArgs.');';
        $lines[] = '';
        $lines[] = '        return $this;';
    } else {
        $lines[] = '        return parent::'.$method->getName().'('.$callArgs.');';
    }

    $lines[] = '    }';
    $lines[] = '';
}

if (end($lines) === '') {
    array_pop($lines);
}

$lines[] = '}';
$lines[] = '';

$lines = applyUseStatements($lines);

$targetDir = dirname($targetFile);
if (! is_dir($targetDir)) {
    mkdir($targetDir, 0777, true);
}

file_put_contents($targetFile, implode("\n", $lines));

echo "Generated ".$targetFile.' with '.count($methods)." wrappers.\n";

function buildMethodSignature(ReflectionMethod $method): string
{
    $params = array_map(static fn (ReflectionParameter $p): string => renderParameter($p), $method->getParameters());

    $returnType = '';
    if ($method->hasReturnType()) {
        $rendered = renderType($method->getReturnType());
        if ($rendered !== null) {
            $returnType = ': '.$rendered;
        }
    }

    return 'public function '.$method->getName().'('.implode(', ', $params).')'.$returnType;
}

function buildCallArguments(ReflectionMethod $method): string
{
    $args = [];
    foreach ($method->getParameters() as $parameter) {
        $prefix = $parameter->isVariadic() ? '...' : '';
        $args[] = $prefix.'$'.$parameter->getName();
    }

    return implode(', ', $args);
}

function renderParameter(ReflectionParameter $parameter): string
{
    $chunks = [];
    $type = renderType($parameter->getType());

    if ($type !== null) {
        $chunks[] = $type;
    }

    if ($parameter->isPassedByReference()) {
        $chunks[] = '&';
    }

    if ($parameter->isVariadic()) {
        $chunks[] = '...';
    }

    $chunks[] = '$'.$parameter->getName();

    if ($parameter->isOptional() && ! $parameter->isVariadic() && $parameter->isDefaultValueAvailable()) {
        $chunks[] = '= '.renderDefaultValue($parameter);
    }

    return implode(' ', $chunks);
}

function renderDefaultValue(ReflectionParameter $parameter): string
{
    if ($parameter->isDefaultValueConstant()) {
        $constantName = $parameter->getDefaultValueConstantName();
        if (is_string($constantName)) {
            return $constantName;
        }
    }

    $value = $parameter->getDefaultValue();

    if (is_array($value) && $value === []) {
        return '[]';
    }

    return var_export($value, true);
}

/**
 * @return list<string>
 */
function buildMethodPhpDocLines(ReflectionMethod $method, ?ReflectionType $returnType): array
{
    $lines = extractDocTags($method, ['@param', '@return']);

    $existingParamDocs = [];
    foreach ($lines as $line) {
        if (preg_match('/^@param\s+.+\s+\$([A-Za-z_][A-Za-z0-9_]*)\b/', $line, $m) === 1) {
            $existingParamDocs[$m[1]] = true;
        }
    }

    foreach ($method->getParameters() as $parameter) {
        $name = $parameter->getName();
        if (isset($existingParamDocs[$name])) {
            continue;
        }

        if (renderType($parameter->getType()) === 'array') {
            $lines[] = '@param array<string, mixed> $'.$parameter->getName();
        }
    }

    $hasReturnDoc = false;
    foreach ($lines as $line) {
        if (str_starts_with($line, '@return ')) {
            $hasReturnDoc = true;
            break;
        }
    }

    if ($returnType === null && ! $hasReturnDoc) {
        $lines[] = '@return $this';
    }

    return $lines;
}

/**
 * @param list<string> $prefixes
 * @return list<string>
 */
function extractDocTags(ReflectionMethod $method, array $prefixes): array
{
    $doc = $method->getDocComment();

    if ($doc === false) {
        return [];
    }

    $tags = [];
    foreach (preg_split('/\R/', $doc) ?: [] as $line) {
        if (preg_match('/^\s*\*\s*(.+?)\s*$/', $line, $m) !== 1) {
            continue;
        }

        $content = $m[1];
        foreach ($prefixes as $prefix) {
            if (str_starts_with($content, $prefix.' ')) {
                $tags[] = $content;
                break;
            }
        }
    }

    return $tags;
}

function renderType(?ReflectionType $type): ?string
{
    if ($type === null) {
        return null;
    }

    if ($type instanceof ReflectionNamedType) {
        $name = $type->getName();

        if (! $type->isBuiltin() && ! in_array($name, ['self', 'parent', 'static'], true)) {
            $name = '\\'.$name;
        }

        if ($type->allowsNull() && $name !== 'mixed' && $name !== 'null') {
            return '?'.$name;
        }

        return $name;
    }

    if ($type instanceof ReflectionUnionType) {
        return implode('|', array_map(static fn (ReflectionType $t): string => normalizeTypeName($t, true), $type->getTypes()));
    }

    if ($type instanceof ReflectionIntersectionType) {
        return implode('&', array_map(static fn (ReflectionType $t): string => normalizeTypeName($t, true), $type->getTypes()));
    }

    return null;
}

function normalizeTypeName(?ReflectionType $type, bool $ignoreNullable = false): string
{
    if ($type instanceof ReflectionNamedType) {
        $name = $type->getName();
        if (! $type->isBuiltin() && ! in_array($name, ['self', 'parent', 'static'], true)) {
            $name = '\\'.$name;
        }

        if (! $ignoreNullable && $type->allowsNull() && $name !== 'mixed' && $name !== 'null') {
            return '?'.$name;
        }

        return $name;
    }

    if ($type instanceof ReflectionUnionType) {
        return implode('|', array_map(static fn (ReflectionType $t): string => normalizeTypeName($t, true), $type->getTypes()));
    }

    if ($type instanceof ReflectionIntersectionType) {
        return implode('&', array_map(static fn (ReflectionType $t): string => normalizeTypeName($t, true), $type->getTypes()));
    }

    return '';
}

/**
 * Replace FQCN usages with short names and insert use statements.
 *
 * @param list<string> $lines
 * @return list<string>
 */
function applyUseStatements(array $lines): array
{
    $fqcnPattern = '/\\\\[A-Za-z_][A-Za-z0-9_\\\\]*/';
    $fqcnByShortName = [];
    $conflictingShortNames = [];

    foreach ($lines as $line) {
        if (str_starts_with($line, 'namespace ') || str_starts_with($line, 'use ')) {
            continue;
        }

        if (preg_match_all($fqcnPattern, $line, $matches) === false) {
            continue;
        }

        foreach ($matches[0] as $fqcnWithSlash) {
            $fqcn = ltrim($fqcnWithSlash, '\\');
            $shortName = basename(str_replace('\\', '/', $fqcn));

            if (! isset($fqcnByShortName[$shortName])) {
                $fqcnByShortName[$shortName] = $fqcn;
                continue;
            }

            if ($fqcnByShortName[$shortName] !== $fqcn) {
                $conflictingShortNames[$shortName] = true;
            }
        }
    }

    foreach (array_keys($conflictingShortNames) as $shortName) {
        unset($fqcnByShortName[$shortName]);
    }

    if ($fqcnByShortName === []) {
        return $lines;
    }

    $replacementMap = [];
    foreach ($fqcnByShortName as $shortName => $fqcn) {
        $replacementMap['\\'.$fqcn] = $shortName;
    }

    foreach ($lines as $index => $line) {
        if (str_starts_with($line, 'namespace ') || str_starts_with($line, 'use ')) {
            continue;
        }

        $lines[$index] = strtr($line, $replacementMap);
    }

    asort($fqcnByShortName);
    $useLines = array_map(
        static fn (string $fqcn): string => 'use '.$fqcn.';',
        array_values($fqcnByShortName)
    );

    $namespaceIndex = null;
    foreach ($lines as $index => $line) {
        if (str_starts_with($line, 'namespace ')) {
            $namespaceIndex = $index;
            break;
        }
    }

    if ($namespaceIndex === null) {
        return $lines;
    }

    $insertAt = $namespaceIndex + 1;
    $deleteCount = 0;
    if (($lines[$insertAt] ?? null) === '') {
        $deleteCount = 1;
    }

    $block = [''];
    foreach ($useLines as $useLine) {
        $block[] = $useLine;
    }
    $block[] = '';

    array_splice($lines, $insertAt, $deleteCount, $block);

    return $lines;
}
